on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  check-production-model:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install mlflow
        pip install pyyaml
        pip install requests

    - name: Check for new production model
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python mlflow_web_hook.py