"""
cron parameters: 
- minute: The minute at which the cron job should run. Accepts values from 0 to 59 or '*' for any value.
- hour: The hour at which the cron job should run. Accepts values from 0 to 23 or '*' for any value.
- day_of_month: The day of the month on which the cron job should run. Accepts values from 1 to 31 or '*' for any value.
- month: The month in which the cron job should run. Accepts values from 1 to 12 or '*' for any value.
- day_of_week: The day of the week on which the cron job should run. Accepts values from 0 to 6 (Sunday to Saturday) or '*' for any value.

"""
on:
  schedule:
    - cron:  '0 0 1 1 *'  # Runs once a year on January 1st at 12am

jobs:
  check-production-model:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install mlflow
        pip install pyyaml
        pip install requests

    - name: Check for new production model
      run: python mlflow_web_hook.py  # This script should use MLflow's REST API to check for a new production model