name: Build Docker Image from MLflow Model URI, Push to Docker Hub, and Update EC2

on:
  repository_dispatch:
    types: [new-model-version]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: prod

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install mlflow
        pip install pyyaml

    - name: Read config.yaml and set environment variables
      run: |
        echo "MLFLOW_TRACKING_URI=$(python -c 'import yaml; print(yaml.safe_load(open("config.yaml"))["tracking_uri"])')" >> $GITHUB_ENV
        echo "MLFLOW_MODEL_URI=models:/$(python -c 'import yaml; print(yaml.safe_load(open("config.yaml"))["model_name"])')/Production" >> $GITHUB_ENV
        echo "DOCKER_IMAGE_NAME=$(python -c 'import yaml; print(yaml.safe_load(open("config.yaml"))["docker_image_name"])')" >> $GITHUB_ENV
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build and tag the Docker image
      run: docker build -t "${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:new" . --file Dockerfile

    - name: Push Docker image to Docker Hub
      run: docker push "${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:new"

    - name: Update EC2 instance
      run: |
        echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > key
        chmod 400 key
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i key ec2-user@${{ secrets.EC2_IP }} << EOF
          docker stop movie_sentiment || true
          docker rm movie_sentiment || true
          docker rmi "${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:new" || true
          docker pull "${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:new"
          docker run -d --name sentiment -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -p 8501:8501 ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
          EOF