name: Build Docker Image from MLflow Model URI, Push to Docker Hub, and Update EC2

on:
  repository_dispatch:
    types: [new-model-version]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: prod

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: SSH and Update EC2 instance
      run: |
        echo "${{ secrets.SSH_KEY }}" > my_key.pem
        chmod 600 my_key.pem
        ssh -v -o StrictHostKeyChecking=no -i my_key.pem ec2-user@${{ secrets.EC2_IP }} << EOF
          docker stop movie_sentiment || true
          docker rm movie_sentiment || true
          docker rmi "${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:new" || true
          docker pull "${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:new"
          docker run -d --name sentiment -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -p 8501:8501 ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
        EOF